#!/bin/bash

# MAKE SURE THAT THE FOLLOWING FINGERPRINT IS CORRECT
whonixFingerprint="6E979B28A6F37C43BE30AFA1CB8D50BB77BB3C48"

# Downloads the canary
wget -O /tmp/whonix-canary.txt https://raw.githubusercontent.com/Whonix/canary/master/canary.txt &> /dev/null || $(echo "[ERROR] Download of canary.txt FAILED."; exit 1)
wget -O /tmp/whonix-canary.txt.asc https://raw.githubusercontent.com/Whonix/canary/master/canary.txt.asc &> /dev/null || $(echo "[ERROR] Download of canary.txt.asc FAILED."; exit 1)

# Verifies the signature and shows you the canary using less if it is correct
echo -n "" > /tmp/sign
gpg --verify /tmp/whonix-canary.txt.asc /tmp/whonix-canary.txt &> /tmp/sign && grep "$whonixFingerprint" /tmp/sign > /dev/null &&\
less /tmp/whonix-canary.txt &&\
echo "[OK] The Whonix canary is correctly signed" && exit 0\
|| echo "[WARNING] The Whonix canary does not appear to be correctly signed. Make sure that you have imported the correct key. Do not trust anything written in the canary! The canary is located at /tmp/whonix-canary.txt" ; exit 1

# Check whether certain sentences have changed in the canary.
warrantString="2. No warrants have ever been served on the Whonix Project; for example, to hand out the private signing keys or to introduce backdoors."
grep -Fxq $warrantString /tmp/whonix-canary.txt || $(echo "[WARNING] The Whonix canary is does not mention \"No warrants have ever been served on the Whonix Project;\". The canary file can be read at /tmp/whonix-canary.txt" ; exit 1)

# OPTIONAL: Remove all the files after verifying them
# yes | rm /tmp/whonix-canary.txt* &> /dev/null
