#!/bin/sh
#-----------------------WHONIX CANARY----------------------
whonixFingerprint="6E979B28A6F37C43BE30AFA1CB8D50BB77BB3C48" # MAKE SURE THAT THE FOLLOWING FINGERPRINT IS CORRECT
wget -O /tmp/whonix-canary.txt https://raw.githubusercontent.com/Whonix/canary/master/canary.txt &> /dev/null || $(echo "[ERROR] Download of canary.txt FAILED."; exit 1)
wget -O /tmp/whonix-canary.txt.asc https://raw.githubusercontent.com/Whonix/canary/master/canary.txt.asc &> /dev/null || $(echo "[ERROR] Download of canary.txt.asc FAILED."; exit 1)

gpg --verify /tmp/whonix-canary.txt.asc /tmp/whonix-canary.txt &&\
less /tmp/whonix-canary.txt &&\
echo "[OK] The Whonix canary is correctly signed"\
|| echo "[WARNING] The Whonix canary does not appear to be correctly signed. Make sure that you have imported the correct key. For now do not trust anything written in the canary as being written by the Whonix lead developer."&& exit 1

warrantString="2. No warrants have ever been served on the Whonix Project; for example, to hand out the private signing keys or to introduce backdoors."
grep -Fxq $warrantString /tmp/whonix-canary.txt || $(echo "[WARNING] The Whonix canary is does not mention \"No warrants have ever been served on the Whonix Project;\". The canary file can be read at /tmp/whonix-canary.txt" && exit 1)

#OPTIONAL: Remove all the files after verifying them
# yes | rm /tmp/whonix-canary.txt* &> /dev/null




#wget -O canary.txt https://raw.githubusercontent.com/QubesOS/qubes-secpack/master/canaries/canary-023-2020.txt &> /dev/null
#wget -O joanna.sig https://raw.githubusercontent.com/QubesOS/qubes-secpack/master/canaries/canary-023-2020.txt.sig.joanna &> /dev/null 
#wget -O marmarek.sig https://raw.githubusercontent.com/QubesOS/qubes-secpack/master/canaries/canary-023-2020.txt.sig.marmarek &> /dev/null
#wget -O simon.sig https://raw.githubusercontent.com/QubesOS/qubes-secpack/master/canaries/canary-023-2020.txt.sig.simon &> /dev/null
#gpg --no-default-keyring --keyring ./keys/qubes/joanna-master-key.asc --verify joanna.sig canary.txt
#gpg --no-default-keyring --keyring ./keys/qubes/marmarek.asc --verify marmarek.sig canary.txt
#gpg --no-default-keyring --keyring ./keys/qubes/hw42.asc --verify simon.sig canary.txt
