#!/bin/sh
xwallpaper --stretch .config/wallpaper &
newsboat -x reload &
xdg-mime default org.pwmt.zathura.desktop application/pdf
xset r rate 300 50

echo "power on\nquit" | bluetoothctl

mpd ; mpc random on ; mpc ls | mpc add ; mpc play ; mpc next

dwmblocks &
~/.scripts/bluetooth_connect
