#!/bin/sh

Xresources=$HOME"/.Xresources"

[ -n "$1" ] && Xresources=$1

ST_FOLDER=$HOME"/Programs/st-0.8.4"
echo "static const char *colorname[] = {" > $ST_FOLDER"/colors.h"
sed "s/\!.*//g; /^$/ d;/color/!d;s/*.color//g;s/^/[/g;s/:/]=/g;s/#/\"#/g;s/$/\",/g" $Xresources >> $ST_FOLDER"/colors.h"
echo "};" >> $ST_FOLDER"/colors.h"
cd $ST_FOLDER
sudo make clean install
