#!/bin/bash

function audio()
{
	audio=$(amixer -c 1 sget Master | awk -F"[][]" '/dB/ { print $2 }')
	[[ -z $audio ]] && audio=$(amixer -c 2 sget Master | awk -F"[][]" '/dB/ { print $2 }')
	echo -n $audio
}

function getRam()
{
	free -m | awk -F ' ' 'FNR == 2{print $3}'
}

function currentTime()
{
	date +%T
}

function currentDate()
{
	date +%d/%m-%Y
}

function MPDCurrent()
{
	[ -z $(mpc current) ] && echo "None" || mpc current | sed "s/.mp3//"
}

function MPDVolume()
{
	mpc volume | sed "s/volume: //"
}

function week()
{
	week=$(date +%V)
	echo -n $week
}

function is_internet_down()
{
	cat /sys/class/net/enp5s0/operstate
}

function check_mail()
{
	ls ~/.config/neomutt/mailbox/School/inbox/new | wc -l
}

function get_rss()
{
	newsboat -x print-unread > /dev/null && (newsboat -x print-unread | awk -F ' ' '{print $1}') || echo "?"
}

xsetroot -name "\
   Mail: $(check_mail)\
 | Music: $(MPDCurrent) $(MPDVolume)\
 | $(currentTime) $(currentDate) $(week)\
 | Volume: $(audio)\
 | $(is_internet_down)
"
