#!/bin/bash
selected=$HOME"/images/wallpapers/wallpapers/"$(ls -1 $HOME/images/wallpapers/wallpapers | dmenu -l 15)
rm $HOME/.config/wallpaper
ln -s $selected $HOME/.config/wallpaper
xwallpaper --stretch $HOME/.config/wallpaper
